default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima46396_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima46396_test
  pool: 20

production:
  <<: *default
  adapter: mysql2
  database: furima46396_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock